### ISSUE TITLE
watchseries.cyou

### ISSUE THREAD

**Issue by escortrs** [Blindspot76/e2iPlayer#17]
Hello,

Could you please take a look at host bluewatchseries, it has been working fine but now it displays "No item to display" on all categories.

Thank you for your time.

**Comment by Blindspot76** [comment]
Hello,

"Could you please take a look at host bluewatchseries, it has been working fine but now it displays "No item to display" on all categories."

Thank you for notifying me, but next time you should check the website, too. None of the categories are working on bluewatchseries website. The host would work just fine, but since the site does not... just wait, they will fix it. I suppose.

I hope you are well in these troubling times.
